---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack
spec:
  receivers:
    - name: "null"
    - name: slack
      slackConfigs:
      - apiURL:
          key: apiURL
          name: alertmanager-slack
        channel: '#demoapp'
        sendResolved: true
        text: '{{ template "slack.rancher.text" . }}'
  route:
    continue: true
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 2h
    repeatInterval: 5m
    receiver: "null"
    routes:
    - continue: true
      group_interval: 5m
      group_wait: 30s
      matchers:
        - matchType: =
          name: severity
          value: critical
      receiver: slack
---
apiVersion: v1
data:
  apiURL: >-
     xxxxxx
kind: Secret
metadata:
  name: alertmanager-slack
