---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: webex
spec:
  receivers:
    - name: "null"
    - name: webex
      webexConfigs:
      - apiURL: 'https://webexapis.com/v1/messages'
        httpConfig:
          authorization:
            type: Bearer
            credentials:
              key: WEBEX_TOKEN
              name: alertmanager-webex
        roomID: 'xxxxx'
        sendResolved: true
        message: '{{ template "webex.text_multiple" . }}'
  route:
    continue: true
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 1m
    receiver: "null"
    routes:
    - matchers:
        - matchType: =~
          name: alertname
          value: PrometheusOutOfOrderTimestamps
      receiver: 'null'
    - continue: true
      matchers:
        - matchType: =~
          name: severity
          value: critical|warning|info
      receiver: webex
---
apiVersion: v1
data:
  WEBEX_TOKEN: >-
    xxxxx
kind: Secret
metadata:
  name: alertmanager-webex
