---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: webex
spec:
  receivers:
  - name: "null"
  - name: webex
    webhookConfigs:
    - httpConfig:
        tlsConfig: {}
      sendResolved: true
      url: http://webex-receiver.demoapp:9091/alertmanager
  route:
    continue: true
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 2h
    repeatInterval: 5m
    receiver: "null"
    routes:
    - continue: true
      group_interval: 5m
      group_wait: 30s
      matchers:
        - matchType: =
          name: severity
          value: critical
      receiver: webex
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-webex
type: Opaque
data:
  WEBEX_ROOM: >-
    xxxxx
  WEBEX_TOKEN: >-
    xxxxx
