apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sSELinuxWorkloads
metadata:
  name: policy-for-selinux-workloads
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
  parameters:
    exemptImages: []
    allowedSELinuxOptions:
      - user: RunAsAny
