apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sAllowPrivilegeEscalationContainerWorkloads
metadata:
  name: disallow-privilege-escalation-container-workloads
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
  parameters:
    exemptImages: []
