apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sSeccompProfile
metadata:
  name: ensure-seccomp-profile-set-to-docker-default
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptImages: []
    allowedProfiles:
    - runtime/default
    - docker/default
    - not configured #in case security context is not present
