apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sDisallowSharedHostPIDAndIPCNamespaces
metadata:
  name: disallow-shared-pid-and-ipc-namespaces
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
