apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sAllowPrivilegeEscalationContainerWorkloads
metadata:
  name: disallow-privilege-escalation-container-workloads
  labels:
    type: global
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
