apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sReadOnlyRootFilesystemWorkloads
metadata:
  name: must-have-readonlyrootfilesystem-workloads
  labels:
    type: global
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
