apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sBlockWildcardIngress
metadata:
  name: block-wildcard-ingress
  labels:
    type: global
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
