apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sAllowedVolumeTypes
metadata:
  name: allowed-volume-types
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    volumes:
      - configMap
      - emptyDir
      - projected
      - secret
      - downwardAPI
      - persistentVolumeClaim
