apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sHostNetworkUsage
metadata:
  name: policy-for-host-network-usage
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptImages: []
    hostNetwork: true
    min: 80
    max: 9000
