apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sBlockPodsOnEtcdAndControlplane
metadata:
  name: block-pods-on-etcd-and-controlplane
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    exemptImages: []
