apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sAllowedReposWorkloads
metadata:
  name: repo-is-from-trusted-registry-workloads
  labels:
    type: global
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
  parameters:
    exemptImages: []
    repos:
      - dockerhub.devops.telekom.de/
      - artifactory.devops.telekom.de/
      - registry.devops.telekom.de/
      - registry-internal.devops.telekom.de/
      - crm-fn-wbench.workbench.telekom.de/
      - sdm-wbench.workbench.telekom.de/
      - mtr.devops.telekom.de/
