apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sCapabilitiesWorkloads
metadata:
  name: caask8scapabilitiesworkloads
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
  parameters:
    exemptImages: []
    requiredDropCapabilities: ["ALL"]
