apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sAllowedVolumeTypesWorkloads
metadata:
  name: allowed-volume-types-workloads
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
  parameters:
    exemptImages: []
    volumes:
      - configMap
      - emptyDir
      - projected
      - secret
      - downwardAPI
      - persistentVolumeClaim
      # needed for dynatrace
      - csi
