apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CaaSK8sPrivilegedContainer
metadata:
  name: disallow-privileged-container
  labels:
    type: namespaced
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
