apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 2000
            supplementalGroups: [2000]
          containers:
            - name: backup-container
              image: dockerhub.devops.telekom.de/busybox
              command:
                [
                  "sh",
                  "-c",
                  "echo 'backing up the database'; sleep 10; echo 'backup complete'",
                ]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 2000
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
