apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-web-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cool-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cool-web-app
    spec:
      containers:
        - image: mtr.devops.telekom.de/mcsps/python-flask:demo
          name: cool-web-app
          ports:
            - containerPort: 9091
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: APP
              value: "demo"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        supplementalGroups:
          - 1000
      terminationGracePeriodSeconds: 3
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
